name = "DiffEqCallbacks"
uuid = "459566f4-90b8-5000-8ac3-15dfb0a30def"
version = "4.11.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"

[extensions]
DiffEqCallbacksFunctorsExt = "Functors"

[compat]
ADTypes = "1.9.0"
Aqua = "0.8"
ConcreteStructs = "0.2.3"
DataInterpolations = "5, 6"
DataStructures = "0.18.13, 0.19.0"
DiffEqBase = "6.155.4"
DifferentiationInterface = "0.6.1, 0.7"
ForwardDiff = "0.10.36"
Functors = "0.5"
JET = "0.9, 0.10, 0.11.2"
LinearAlgebra = "1.10"
Markdown = "1.10"
NonlinearSolve = "3.14, 4"
ODEProblemLibrary = "1.0.0"
OrdinaryDiffEqBDF = "1.3.0"
OrdinaryDiffEqLowOrderRK = "1.2.0"
OrdinaryDiffEqNonlinearSolve = "1.5.0"
OrdinaryDiffEqRosenbrock = "1.8.0"
OrdinaryDiffEqTsit5 = "1.1.0"
OrdinaryDiffEqVerner = "1.1.1"
Pkg = "1.10.0"
PrecompileTools = "1.2"
QuadGK = "2.9"
RecipesBase = "1.3.4"
RecursiveArrayTools = "3.27"
SciMLBase = "2.54"
StaticArrays = "1.9.7"
StaticArraysCore = "1.4"
Sundials = "4.19.2"
Test = "1.10"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADTypes", "Aqua", "DataInterpolations", "ForwardDiff", "JET", "Pkg", "NonlinearSolve", "ODEProblemLibrary", "OrdinaryDiffEqBDF", "OrdinaryDiffEqLowOrderRK", "OrdinaryDiffEqNonlinearSolve", "OrdinaryDiffEqTsit5", "OrdinaryDiffEqRosenbrock", "OrdinaryDiffEqVerner", "QuadGK", "StaticArrays", "Test", "Functors"]
