name = "DiffEqCallbacks"
uuid = "459566f4-90b8-5000-8ac3-15dfb0a30def"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "4.4.1"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
ADTypes = "1.9.0"
Aqua = "0.8"
ComponentArrays = "0.15.18"
ConcreteStructs = "0.2.3"
DataInterpolations = "4.6, 5, 6"
DataStructures = "0.18.13"
DiffEqBase = "6.155.3"
DifferentiationInterface = "0.6.1, 0.7"
ForwardDiff = "0.10.36"
Functors = "0.5"
JLArrays = "0.1, 0.2"
LinearAlgebra = "1.10"
Markdown = "1.10"
NonlinearSolve = "3.14, 4"
ODEProblemLibrary = "0.1.8"
OrdinaryDiffEqBDF = "1.3.0"
OrdinaryDiffEqLowOrderRK = "1.2.0"
OrdinaryDiffEqNonlinearSolve = "1.5.0"
OrdinaryDiffEqRosenbrock = "1.8.0"
OrdinaryDiffEqTsit5 = "1.1.0"
OrdinaryDiffEqVerner = "1.1.1"
QuadGK = "2.9"
RecipesBase = "1.3.4"
RecursiveArrayTools = "3.27"
SciMLBase = "2.54"
SciMLSensitivity = "7.68"
StaticArrays = "1.9.7"
StaticArraysCore = "1.4"
Sundials = "4.19.2"
Test = "1.10"
Tracker = "0.2.35"
Zygote = "0.6.69"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ADTypes", "Aqua", "ComponentArrays", "DataInterpolations", "ForwardDiff", "JLArrays", "NonlinearSolve", "ODEProblemLibrary", "QuadGK", "OrdinaryDiffEqBDF", "OrdinaryDiffEqLowOrderRK", "OrdinaryDiffEqNonlinearSolve", "OrdinaryDiffEqTsit5", "OrdinaryDiffEqRosenbrock", "OrdinaryDiffEqVerner", "SciMLSensitivity", "StaticArrays", "Test", "Tracker", "Zygote"]
